- Taskfile.yml
- tests_toplevel/test_config.py
Internally, Taskfile has been replacing our use of Makefile and PyInvoke.
It allows for easy discovery of tasks; and is a language-neutral task runner.
The taskfile is structured in a way that allows for standalone e2e testing, while
being injectable so that our monorepo can run a full e2e test.
Invocations:
```
task -l
task --list-all
task install
task test:e2e:public
```
> chore: Introduce a Taskfile to act as our task-runner

- docs/README.md
- docs/dpdocsutils/dpdocsutils/previews.py
- docs/poetry.lock
- docs/pyproject.toml
- fix: Allow falling back to using pyppeteer's downloaded chromium
- chore: change dpdocsutils to be an editable dependency
> fix: Docs build on Linux

- Taskfile.yml
- dev/Taskfile.template.yml
- docs/README.md
- docs/Taskfile.yml
Utilise Cloudflare Pages for Docs hosting.
Cloudflare will publish the page to your branch name, and to the current commit hash.
As part of this, a think Taskfile has been introduced to allow for self-discovery of projects + commands for the docs project.
CI changes will follow in a separate PR once we're done with manual testing
> Chore: Introduce Deployments for the new Docs page

- projects/python-client/.gitignore
- projects/python-client/README.md
- projects/python-client/pyproject.toml
This is a hack just to get a deploy working with the correct Readme.
We can decide what each README should contain in a followup
> fix: Copy the repo readme into the projects directory

- CONTRIBUTING.md
- Clean up headers
- Point to the new Community Areas
- expose the e2e testing limitation
- document the new directory structure
To note:
Currently only addresses the top-level Contributing Guide, I'm not looking to set them up in this PR as I'd like to chat with someone about them first.
For convenience, [rendered view](https://github.com/datapane/datapane/blob/chore/dev-contributions/CONTRIBUTING.md)
> Update the Contributing Docs ready for Open Contributions

- .pre-commit-config.yaml
fixes https://3.basecamp.com/5309418/buckets/26389214/todos/5133636320
- Add `vue-eslint-parser` as an `additional_dependency` in pre-commit config so that it's available as a node module for `ESLint`
> Fix `vue-eslint-parser module not found` ESlint error

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- Taskfile.yml
- projects/web-components/Taskfile.yml
- Introduces some tooling to help with generating/using the local-reports bundle (run `task -l` for more details)
- Setup a base workflow for running builds
> Chore: Build docs on PR + default branch

- docs/docs/guides/accessing-data-in-python/accessing-data-in-python.ipynb
- docs/docs/guides/accessing-data-in-python/top_queries.csv
Thanks!
Addressing comment from our Discord https://discord.com/channels/983736148746715158/999322544895180901/1003977799662571600:
> Pytrends hits Google, which is doing bot detection.
> We're likely to see more 429s: https://github.com/datapane/datapane/runs/7629659533?check_suite_focus=true#step:11:130
> Suggest we only use publicly available APIs
The PyTrends operations have been switched to a markdown cell. The cell now includes code to save the data to a CSV.
In the following code cell, this data is loaded into a DataFrame and used to create a …
> Cache Google Trends data in docs

- projects/python-client/tests/client/e2e/test_reports.py
Fix for test that failed on deployment due to different config - https://github.com/datapane/datapane-hosted/runs/8088926100?check_suite_focus=true#step:13:2052
I rewrote to use a more robust pattern - the `sorted()` logic was in fact only appropriate for the `tags` field which is unsorted by nature, for other fields we can't assume it. So it's easier to just list the fields.
> Fixed E2E test that failed when run against prod

- projects/web-components/package-lock.json
- projects/web-components/package.json
- Roll back JS `vega-lite` package to v4, as the `altair` python lib doesn't support `vega-lite@5` yet (https://github.com/altair-viz/altair/issues/2425)
> Match python and JS Altair libraries

- projects/python-client/src/datapane/client/commands.py
- projects/python-client/src/datapane/client/utils.py
- projects/python-client/tests/client/e2e/test_library.py
Thanks!
fixes #182 
- Datapane updated to use `--dp-parameters` rather than `--parameters` and `-p`. This is the case for `DPMode.LIBRARY`, and the `run()`, `create()`, and `update()` commands (@mands will this break CI?).
- Added tests in `test_library.py` for #182 (a CLI command that imports datapane).
> Fix 182 CLI args parsing

- projects/python-client/src/datapane/common/df_processor.py
Thanks!
fixes #274
Remove the bipartite_to_binary DataTable optimisation. 
Whilst it did reduce file size, the output was not desirable by some users (e.g. #274). We should re-visit this in future as it's a useful (and common) optimisation!
> Fix 274 Remove binary column processing for DataTable

- projects/python-client/src/datapane/__init__.py
- projects/python-client/src/datapane/client/commands.py
- projects/python-client/src/datapane/client/utils.py
- projects/python-client/tests/client/e2e/test_library.py
Fixes #182
- change from `--dp-parameter` to `--parameter` (or `-p`), reverting 6cf4f2795c3dd484262f9bdfc64bf4a9b5e82c72 and c86d9125928f4a074ca62eac61cde1e09bda3255, to avoid breaking existing `datapane` CLI usage
- Don't parse command line automatically in library mode. Instead we provide a `load_params_from_command_line` function to do this. Since the original functionality was not documented anywhere, we probably don't need to document this, but can just leave the function somewhere it should be discovered fairly easily for those that need it.
> Improved fix for #182

- .github/workflows/build-docs.yml
- .github/workflows/test-datapane.yml
- .github/workflows/update-docs.yml
- docs/poetry.lock
- docs/pyproject.toml
- projects/python-client/poetry.lock
- projects/python-client/pyproject.toml
- poetry 1.1 takes too long to resolve loose dependencies
You can continue to use poetry 1.1 for executing, just don't change the lockfile, lest we flipflop.
> chore: bump to poetry 1.2.0

- projects/web-components/cypress.config.ts
- projects/web-components/cypress/e2e/org/app-run.cy.js
- projects/web-components/cypress/e2e/public/report-render.cy.js
- projects/web-components/cypress/support/commands.js
- Increase cypress element find timeout from 8s to 20s, to prevent timeout failures in CI
> Increase cypress tests timeout

- docs/nbbuild.sh
- projects/python-client/src/datapane/client/api/report/core.py
- This lets us point Docs to the Staging CDN for the time being
> fix(docs): Allow setting the CDN Base via an environment variable

- projects/python-client/src/datapane/client/config.py
- projects/python-client/tests_toplevel/test_config.py
- default is now cloud.datapane.com
- upgrade existing configs that used the last default of datapane.com
Testing:
- fresh 'datapane login' without config should add 'server: https://cloud.datapane.com'
- manually change config to 'https://datapane.com'
- 'datapane ping' will upgrade the config, and confirm it connected to 'https://cloud.datapane.com'
> chore(python-client): Upgrade the default server to cloud.datapane.com

- projects/python-client/pyproject.toml
Updates the include rules, they're a little looser as there's more than just `local-report.*`
- README and License are explicit now, as we need them for Conda (they were implicitly included before)
> fix: explicitly include the report resources in builds

- projects/web-components/shared/dp-track.ts
We traditionally used localStorage for PostHog, but we are now cross-domain (e.g. @, cloud., docs.) and localStoage doesn't work cross-domain. I've replaced with the default implementation which uses cross-domain cookies instead.
> Move away from localStorage for PostHog

- projects/web-components/report/src/components/ReportComponent.vue
- projects/web-components/report/src/data-model/types.ts
- projects/web-components/shared/dp-track.ts
- Fix if/else statement so that remote views aren't registered in local reports
- Remove `disableTrackViews` prop which was only previously used by the report builder
> Fix remote report view being emitted in local reports

- projects/python-client/src/datapane/client/api/ipython_utils.py
Thanks!
- @antdking reported that `ipynbname` was failing in a VS Code notebook.
- We compared our environments and tried to reproduce it on my machine (Mac OS) with no success.
- It seems @antdking's VS Code does not launch a full Jupyter server.
We try to get the notebook path using a VSCode-specific key in the user namespace variable first. If it's not there, we fall back to the `ipynbname` approach.
> Support cells to blocks conversion when full Jupyter server is missing in VS Code

- docs/nbbuild.sh
Some calls request the browser be opened.
Disable browser discovery while building docs
> fix: Docs opens pages in browser while building

- projects/python-client/src/datapane/client/api/files.py
Thanks!
fixes #320 
- We're now using "tight" bounding box calculation.
Matplotlib figures appeared to be cropped. This is because we were saving to SVG without setting the bounding box.
> Better Matplotlib support - tight bounding box to avoid clipping

- README.md
Thanks!
fixes #
- Examples link now goes to "#demos-and-examples" section in README. The old https://datapanem.com/showcase page no longer exists.
- Updated our tagline and description to the one on our new website.
- changed "report" terminology to "app"
- changed dp.Report objects to dp.App
- Updated `conda` install instructions from Datapane version from 0.15.1 to 0.15.4
- Removed Forum section, added Feedback section (links to nolt).
- Updated all links in the "#demos-and-examples" section to their new cloud.datapane.com addresses.
- Datapane Cloud …
> Update README content and fix links

- projects/web-components/report/src/data-model/blocks.ts
- projects/web-components/report/src/data-model/report-store.ts
fixes https://github.com/datapane/datapane/issues/325
- Fix the `isSingleBlockEmbed` function to recurse through all layout block types instead of just groups
> fix: root-level single select blocks being treated as single-block embeds

- docs/poetry.lock
- docs/pyproject.toml
- projects/python-client/poetry.lock
- projects/python-client/pyproject.toml
- projects/web-components/package-lock.json
- projects/web-components/package.json
- projects/web-components/report/src/data-model/datatable/arrow-utils.ts
- Change pyarrow range to `>=6, <11` in datapane `python-client/` and `docs/`
- Upgrade arrow npm lib to `^10.0.0`
Tested manually on demo report datatable and `vega_datasets.cars`, [test code here](https://gist.github.com/Buroni/65d52df318e43ff01c2f67dc8f3c273e)
> Upgrade arrow to v10
