datapane/datapane

- webui/tailwind.config.js
- Add local_report template file to tailwind config
> add local_report template file to tailwind config

- README.md
Thanks!
- Add Datapane in 3 minutes video to README
> Add Datapane in 3 minutes video to README

- .github/workflows/test-datapane.yml
- (chore) Trigger only on changes to `python-client` project
> Update datapane tests trigger

- projects/python-client/src/datapane/client/api/files.py
- projects/python-client/src/datapane/client/api/report/blocks.py
- projects/python-client/src/datapane/client/commands.py
- projects/python-client/src/datapane/client/utils.py
- projects/python-client/src/datapane/common/datafiles.py
- projects/python-client/tests/client/e2e/test_apps.py
- projects/python-client/tests/client/e2e/test_reports.py
For same reasons as in https://github.com/datapane/datapane-hosted/pull/957
> Replaced use of non-standard ellipsis with standard 'pass' idiom

- docs/docs/quickstart.ipynb
- projects/python-client/src/datapane/__init__.py
- projects/python-client/src/datapane/client/api/__init__.py
- projects/python-client/src/datapane/client/api/user.py
- projects/python-client/src/datapane/client/commands.py
- projects/python-client/src/datapane/resources/templates/hello/hello.py
Removes sign-up command from the CLI
> Removed sign-up via the API

- .gitignore
Thanks!
Minor change adding .DS_Store to .gitignore
> Update .gitignore to exclude .DS_Store

- .pre-commit-config.yaml
- projects/python-client/.flake8
- projects/python-client/src/datapane/client/analytics.py
- projects/python-client/src/datapane/client/commands.py
- projects/python-client/src/datapane/common/df_processor.py
- projects/python-client/src/datapane/runner/exceptions.py
- projects/python-client/tests/client/e2e/test_reports.py
These tests are failing our in our [e2e suite](https://github.com/datapane/datapane-hosted/runs/7802094857?check_suite_focus=true), with `AttributeError`. I they should have been removed in 1051d3d as part of #234 - is that correct @mallok-s ? Thanks!
> Removed remaining update_assets tests

- projects/python-client/src/datapane/common/df_processor.py
Thanks!
Converts columns which contain int {0, 1} values to bool
Demonstration below:
booleans_before.html, 21.4 MB
booleans_after.html, 15.5 MB
> chore: Added bipartite to bool conversion

- projects/python-client/src/datapane/client/api/__init__.py
- projects/python-client/src/datapane/client/api/common.py
- projects/python-client/src/datapane/client/api/dp_object.py
- projects/python-client/src/datapane/client/api/report/core.py
- projects/python-client/src/datapane/client/api/runtime.py
- projects/python-client/src/datapane/client/api/teams.py
- projects/python-client/src/datapane/client/api/user.py
- projects/python-client/src/datapane/client/commands.py
- projects/python-client/src/datapane/client/config.py
- projects/python-client/src/datapane/common/utils.py
- projects/python-client/tests/client/e2e/test_apps.py
- projects/python-client/tests/client/e2e/test_reports.py
- projects/python-client/tests/cypress_setup.py
- projects/web-components/cypress.config.ts
- projects/web-components/cypress/e2e/org/app-run.cy.js
- projects/web-components/cypress/e2e/org/report-styling.cy.js
- projects/web-components/cypress/e2e/public/report-styling.cy.js
- projects/web-components/cypress/support/constants.js
- projects/web-components/package-lock.json
- projects/web-components/package.json
Fixes to support the new Multi-tenancy changes coming to Datapane
> Multi-tenancy API fixes

- projects/python-client/poetry.lock
- projects/python-client/pyproject.toml
- projects/python-client/pytest.ini
Same as what we do on dp-server
> tests: Discover environment variables from .env files

- projects/python-client/src/datapane/client/api/user.py
- Updates the login endpoint to use the new interactive login
> Updated client to use new EP (accounts/api-login-token-accept)

- docs/docs/catalogues/templates/index.ipynb
Thanks!
Add new Survey data template to templates catalogue. Screenshot below:
> Add survey template to templates catalogue

- docs/docs/img/releasenotes/cloud.png
- docs/docs/releasenotes.md
- docs/mkdocs.yml
Adds the release notes to the documentation and will be updated on each new point release.
> Add release notes section and content to the docs

- docs/mkdocs.yml
Thanks!
Minor change to docs navigation. Places Timeline entry under the correct heading.
> Update mkdocs.yml to place Timeline under correct heading

- docs/docs/tutorials/datapane-enterprise/report-notifications.ipynb
Thanks!
fixes #
- Tiny change, removing one dead link and Teams mention that I found that was really upsetting me. Wasn't even sure it justified a PR :P
> Removed mention of Teams and the dead link

- projects/python-client/src/datapane/common/report.py
- projects/web-components/cypress/e2e/public/report-styling.cy.js
- projects/web-components/global.ts
- projects/web-components/package-lock.json
- projects/web-components/package.json
- projects/web-components/report/src/components/ReportComponent.vue
- Move public sanitisation to front-end, using `sanitize-html`
We may want to look into the built-in [browser sanitiser API ](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API)when it's more widely supported
> Fix public header sanitisation

- docs/docs/catalogues/blocks/attachment.ipynb
- docs/docs/catalogues/blocks/bignumber.ipynb
- docs/docs/catalogues/blocks/code.ipynb
- docs/docs/catalogues/blocks/datatable.ipynb
- docs/docs/catalogues/blocks/embed.ipynb
- docs/docs/catalogues/blocks/formula.ipynb
- docs/docs/catalogues/blocks/group.ipynb
- docs/docs/catalogues/blocks/html.ipynb
- docs/docs/catalogues/blocks/map.ipynb
- docs/docs/catalogues/blocks/media.ipynb
- docs/docs/catalogues/blocks/page.ipynb
- docs/docs/catalogues/blocks/plot.ipynb
- docs/docs/catalogues/blocks/select.ipynb
- docs/docs/catalogues/blocks/table.ipynb
- docs/docs/catalogues/blocks/text.ipynb
- docs/docs/catalogues/components/calendar-heatmap.ipynb
- docs/docs/catalogues/components/timeline.ipynb
- docs/docs/guides/accessing-data-in-python/accessing-data-in-python.ipynb
- docs/docs/guides/adding-interactive-filters-to-plots/adding-interactive-filters-to-plots.ipynb
- docs/docs/index.ipynb
- docs/docs/quickstart.ipynb
- docs/docs/tutorials/basics/create-an-app.ipynb
- docs/docs/tutorials/blocks/index.ipynb
- docs/docs/tutorials/styling/index.ipynb
- docs/dpdocsutils/dpdocsutils/previews.py
- docs/dpdocsutils/setup.py
Thanks!
fixes #
Embed iFrame instead of screenshot for App output in Docs
> Embed iFrame instead of screenshot for App output in Docs

- projects/python-client/tests/cypress_setup.py
Because we are removing LegacyApp in dp-server and related APIs
See https://github.com/datapane/datapane-hosted/pull/1042 and the test failure: https://github.com/datapane/datapane-hosted/actions/runs/3282202520/jobs/5405606180
> Removed tests that upload apps

- projects/python-client/tests/client/e2e/test_api.py
- projects/python-client/tests/client/e2e/test_cli.py
* Disabled some more tests relating to LegacyApp
> chore: Disabled LegacyApp related tests

- docs/docs/catalogs/templates/index.ipynb
Thanks!
- Adds instructions for custom dp-templates and the `--no-execute` option.
> Add instructions for custom dp-templates
